# Generated by Django 5.2.17 on 2026-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scenario_id', models.CharField(max_length=64)),
                ('shots', models.IntegerField(default=256)),
                ('qber', models.FloatField()),
                ('threshold_tau', models.FloatField(default=0.08)),
                ('fidelity', models.FloatField()),
                ('nonce_used', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('verdict', models.CharField(max_length=64)),
                ('threat_detected', models.BooleanField(default=False)),
                ('threat_category', models.CharField(default='None', max_length=64)),
                ('latency_ms', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
